
### Barcode Check
GET http://localhost:9000/check/123456789

### User total
Get http://localhost:9000/total/123456789/98765

### User all items
Get http://localhost:9000/all/aF63z0R0jlQR7sfOgBAgOCOsQgv1

### Post for new entry
POST http://localhost:9000/entry
Content-Type: application/json

{
    "check" : false,
    "userid" : "12345",
    "barcode" : "123456789",
    "date" : "2020-08-06"

}

### Post for new entry without product being in database
POST http://localhost:9000/entry
Content-Type: application/json

{
    "check" : true,
    "userid" : "12345",
    "barcode" : "987651234",
    "date" : "2020-08-06",
    "name" : "Strawberry Jam",
    "price" : "32.00"

}

### Test
GET http://localhost:9000/test/
