version: "3.2"
services:
  apache-server:
    build: "./views"
    expose:
      - 80
    ports:
      - "8080:80"
    restart: always
  node-server:
    build: "./NODE"
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_DATABASE: "fridgeInv"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "xxmaster"
      MYSQL_ROOT_PASSWORD: "xxmaster"
    ports:
      - "3306:3306"
    networks:
      - backend
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
networks:
  backend:
