version: "3.2"
services:
  apache-server:
    build: "./views"
    expose:
      - 80
    ports:
      - "8080:80"
    restart: always
  node-server:
    build: "./NODE"
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: always
  db:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_DATABASE: "fridgeInv"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "admin"
      # You can use whatever password you like
      MYSQL_PASSWORD: "xxmaster"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "xxmaster"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    networks:
      - backend
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
networks:
  backend:
